$engine: 3
$minFxVersion: 5104
$onesync: legacy
name: ox_esx_recipe
version: 1.4.2
author: DokaDoka
description: Overextended ESX compatible with ox_inventory

tasks:
  ## Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  - action: remove_path
    path: ./resources/[cfx-default]/[gamemodes]

  ## Download and prepare server.cfg, database and icon
  - action: download_github
    src: https://github.com/valounours/ox_recipes
    ref: esx
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/oxpog.png
    dest: ./oxpog.png

  - action: replace_string
    mode: all_vars
    file: ./tmp/recipe/esx.sql

  - action: connect_database
  - action: query_database
    file: ./tmp/recipe/esx.sql

  ## Download bulk esx scripts
  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: main
    subpath: "[esx]"
    dest: ./resources/[esx]

  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: main
    subpath: "[esx_addons]"
    dest: ./resources/[esx_addons]

  ## esx_multicharacter
  - action: remove_path
    path: ./resources/[esx_addons]/esx_multicharacter

  - action: download_github
    src: https://github.com/thelindat/esx_multicharacter
    ref: master
    dest: ./resources/[esx_addons]/esx_multicharacter

  - action: replace_string
    file: ./resources/[esx]/es_extended/config.lua
    search: 'Config.Multichar                = false'
    replace: 'Config.Multichar                = true'

  ## ox_lib
  - action: download_file
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
    path: ./tmp/ox_lib.zip
  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources

  ## oxmysql
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources

  ## ox_inventory
  - action: download_file
    url: https://github.com/overextended/ox_inventory/releases/latest/download/ox_inventory.zip
    path: ./tmp/ox_inventory.zip
  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources

  ## fivem-appearance
  - action: download_file
    url: https://github.com/thelindat/fivem-appearance/releases/latest/download/fivem-appearance.zip
    path: ./tmp/fivem-appearance.zip
  - action: unzip
    src: ./tmp/fivem-appearance.zip
    dest: ./resources/[ox]

  ## ox_appearance
  - action: download_github
    src: https://github.com/overextended/ox_appearance
    ref: main
    dest: ./resources/[ox]/ox_appearance

  ## npwd
  - action: download_file
    url: https://github.com/project-error/npwd/releases/latest/download/npwd.zip
    path: ./tmp/npwd.zip
  - action: unzip
    src: ./tmp/npwd.zip
    dest: ./resources

  - action: query_database
    file: ./resources/npwd/import.sql

  - action: replace_string
    file: ./resources/npwd/config.json
    search: '"useResourceIntegration": false'
    replace: '"useResourceIntegration": true'

  - action: replace_string
    file: ./resources/npwd/config.json
    search: '"level": "silly"'
    replace: '"level": "error"'

  ## esx-npwd
  - action: download_github
    src: https://github.com/overextended/esx-npwd
    ref: main
    dest: ./resources/[esx_addons]/esx-npwd

  ## pma-voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/pma-voice

  ## screenshot-basic
  - action: download_github
    src: https://github.com/project-error/screenshot-basic
    ref: master
    dest: ./resources/screenshot-basic

  ## loadingscreen
  - action: download_github
    src: https://github.com/DokaDoka/pe-basicloading
    ref: oxesx
    dest: ./resources/pe-basicloading

  - action: replace_string
    mode: all_vars
    file:
    - ./resources/pe-basicloading/web/config.js

  ## ipl loader
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[maps]/bob74_ipl

  ## cleanup
  - action: remove_path
    path: ./tmp
  - action: remove_path
    path: ./resources/[esx]/esx_skin
  - action: remove_path
    path: ./resources/[esx]/skinchanger
  - action: remove_path
    path: ./resources/[esx_addons]/esx_accessories
  - action: remove_path
    path: ./resources/[esx_addons]/esx_animations
  - action: remove_path
    path: ./resources/[esx_addons]/esx_barbershop
  - action: remove_path
    path: ./resources/[esx_addons]/esx_clotheshop
  - action: remove_path
    path: ./resources/[esx_addons]/esx_jobs
  - action: remove_path
    path: ./resources/[esx_addons]/esx_phone
  - action: remove_path
    path: ./resources/[esx_addons]/esx_shops
  - action: remove_path
    path: ./resources/[esx_addons]/esx_voice
  - action: remove_path
    path: ./resources/[esx_addons]/esx_weaponshop
  - action: remove_path
    path: ./resources/[esx_addons]/esx_whitelist
